name: Trigger weekly build

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  check-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
      - run: npm install
      - name: Run triggerWeekly.js
        run: node scripts/triggerWeekly.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}